"""empty message

Revision ID: 0fda18ac05d0
Revises: 
Create Date: 2020-11-11 22:14:53.083506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fda18ac05d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_username'), 'customer', ['username'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_type', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=32), nullable=True),
    sa.Column('pane_width', sa.Integer(), nullable=True),
    sa.Column('num_panes', sa.Integer(), nullable=True),
    sa.Column('obscured', sa.Boolean(), nullable=True),
    sa.Column('tempered', sa.Boolean(), nullable=True),
    sa.Column('gas_fill_type', sa.String(length=16), nullable=True),
    sa.Column('lowe3', sa.Boolean(), nullable=True),
    sa.Column('frame_material', sa.String(length=64), nullable=True),
    sa.Column('nailing_flange', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document', sa.BLOB(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('end_employment_date', sa.DateTime(), nullable=True),
    sa.Column('salary_type', sa.String(length=50), nullable=True),
    sa.Column('salary_amount', sa.Float(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    op.create_table('jobsite_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_address_1', sa.String(length=32), nullable=True),
    sa.Column('street_address_2', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number_of_transactions_left', sa.Integer(), nullable=True),
    sa.Column('amount_per_transaction', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.VARCHAR(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_address_1', sa.String(length=32), nullable=True),
    sa.Column('street_address_2', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_address_1', sa.String(length=32), nullable=True),
    sa.Column('street_address_2', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing_address')
    op.drop_table('billing_address')
    op.drop_table('transaction')
    op.drop_table('payment_plan')
    op.drop_table('order_item')
    op.drop_table('jobsite_address')
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('cart_item')
    op.drop_table('agreement')
    op.drop_table('window')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('product')
    op.drop_index(op.f('ix_customer_username'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
