"""empty message

Revision ID: 92537673e9c1
Revises: 1837fae185ae
Create Date: 2020-10-18 03:15:20.326298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92537673e9c1'
down_revision = '1837fae185ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
