"""Created all tables

Revision ID: fa778c0cefcf
Revises: 
Create Date: 2020-10-02 23:10:31.922161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa778c0cefcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('ssn', sa.String(length=9), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('salary_type', sa.String(length=64), nullable=True),
    sa.Column('salary_amount', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('biiling_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address_1', sa.String(length=32), nullable=True),
    sa.Column('street_address_2', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address_1', sa.String(length=32), nullable=True),
    sa.Column('street_address_2', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('window_type', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=32), nullable=True),
    sa.Column('pane_width', sa.Integer(), nullable=True),
    sa.Column('num_panes', sa.Integer(), nullable=True),
    sa.Column('obscured', sa.Boolean(), nullable=True),
    sa.Column('tempered', sa.Boolean(), nullable=True),
    sa.Column('gas_fill_type', sa.String(length=16), nullable=True),
    sa.Column('lowe3', sa.Boolean(), nullable=True),
    sa.Column('frame_material', sa.String(length=64), nullable=True),
    sa.Column('nailing_flange', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('window')
    op.drop_table('mailing_address')
    op.drop_table('biiling_address')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
